project_id = "awhmodyqxysnqkuczgss"

[functions.sitemap]
verify_jwt = false

[functions.handle-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.rss]
verify_jwt = false

[functions.sync-blog-posts]
verify_jwt = false
