// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awhmodyqxysnqkuczgss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aG1vZHlxeHlzbnFrdWN6Z3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTY1MTMsImV4cCI6MjA2OTIzMjUxM30.cjVM4yma8mLNmRB32A84xEI6jZU_gAXOVZguu4XCTqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});